# -*- coding: utf-8 -*-
"""DecisionTree weather.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1igfbSqsLa2AHyUiqSSfRwboNPu-Ea6q1

# **Classificação com Árvore de Decisão**
# Autor: José Norberto Fagundes Isaias
# Mtrcl: 19202785
"""

from sklearn import tree
from sklearn.preprocessing import LabelEncoder
import pandas as pd
df = pd.read_csv('weather.csv', index_col=0)
df = df.drop(['Date', 'Evaporation', 'Sunshine', 'WindDir9am', 'WindDir3pm', 'WindSpeed9am', 'WindSpeed3pm', 'RISK_MM'],axis='columns')
inputs = df.dropna().reset_index(drop=True)

le = LabelEncoder()
inputs['Location'] = le.fit_transform(inputs['Location'])
inputs['WindGustDir'] = le.fit_transform(inputs['WindGustDir'])
inputs['RainToday'] = le.fit_transform(inputs['RainToday'])
inputs['RainTomorrow'] = le.fit_transform(inputs['RainTomorrow'])

target = inputs['RainTomorrow']
inputs = inputs.drop(['RainTomorrow'], axis='columns')

inputs.head()
target.head()

print(inputs)

X, y = inputs.values, target.values

clf = tree.DecisionTreeClassifier(criterion="entropy")
clf = clf.fit(X, y)

import graphviz
feature_names = ['Location',
                 'MinTemp',
                 'MaxTemp',
                 'Rainfall',
                 'WindGustDir',
                 'WindGustSpeed',
                 'Humidity9am',
                 'Humidity3pm',
                 'Pressure9am',
                 'Pressure3pm',
                 'Cloud9am',
                 'Cloud3pm',
                 'Temp9am',
                 'Temp3pm',
                 'RainToday']
target_names = ['Rain', 'Dont Rain']
dot_data = tree.export_graphviz(clf, out_file=None, 
                     feature_names=feature_names,  
                     class_names=target_names,  
                     filled=True, rounded=True,  
                     special_characters=True)  
graph = graphviz.Source(dot_data) 
graph.format = "png"
graph.render("weather-entropy")